import {
  Archive,
  ArrowRight,
  ArrowUpDown,
  AtSign,
  Bell,
  Box,
  Calendar,
  CalendarDays,
  CardSim,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsLeftRight,
  ChevronsRight,
  ChevronsUpDown,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  Download,
  Ellipsis,
  FilePlay,
  Filter,
  Folder,
  Hash,
  Image as ImageIcon,
  LayoutDashboard,
  LifeBuoy,
  Link,
  List,
  ListOrdered,
  Lock,
  LogOut,
  Menu,
  Monitor,
  MoveLeft,
  MoveRight,
  Package,
  Paperclip,
  Pencil,
  Plus,
  PlusCircle,
  Search,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  Table,
  Tag,
  Ticket,
  Trash,
  Trash2,
  TriangleAlert,
  UploadCloud,
  UserRound,
  X,
} from "lucide-react";

const iconMap = {
  "archive": Archive,
  "arrow-right": ArrowRight,
  "arrow-up-down": ArrowUpDown,
  "at-sign": AtSign,
  "bell": Bell,
  "box": Box,
  "calendar": Calendar,
  "calendar-days": CalendarDays,
  "card-sim": CardSim,
  "check": Check,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "chevrons-left": ChevronsLeft,
  "chevrons-left-right": ChevronsLeftRight,
  "chevrons-right": ChevronsRight,
  "chevrons-up-down": ChevronsUpDown,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "circle-plus": CirclePlus,
  "download": Download,
  "ellipsis": Ellipsis,
  "file-play": FilePlay,
  "filter": Filter,
  "folder": Folder,
  "hash": Hash,
  "image": ImageIcon,
  "layout-dashboard": LayoutDashboard,
  "life-buoy": LifeBuoy,
  "link": Link,
  "list": List,
  "list-ordered": ListOrdered,
  "lock": Lock,
  "log-out": LogOut,
  "menu": Menu,
  "monitor": Monitor,
  "move-left": MoveLeft,
  "move-right": MoveRight,
  "package": Package,
  "paperclip": Paperclip,
  "pencil": Pencil,
  "plus": Plus,
  "plus-circle": PlusCircle,
  "search": Search,
  "settings": Settings,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  "smile": Smile,
  "sparkles": Sparkles,
  "table": Table,
  "tag": Tag,
  "ticket": Ticket,
  "trash": Trash,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  "upload-cloud": UploadCloud,
  "user-round": UserRound,
  "x": X,
};

export const Icon = ({ name, className = "h-4 w-4 shrink-0", ...props }) => {
  const Component = iconMap[name];
  if (!Component) return null;
  return <Component className={className} {...props} />;
};

export default Icon;
